### ISSUE TITLE
check here

### ISSUE THREAD

**Issue by dfelleman811** [EricTrainingRev/rubric-generator#1]
Did you want this for loop to be inside the forEach block? Could be causing some unexpected behavior. Especially if you're not getting all requirements with the description.

https://github.com/EricTrainingRev/rubric-generator/blob/fd938d659f81546d7dbe7be9b3341e13d039269d/requirementObjectsPackager.ts#L40

**Comment by EricTrainingRev** [comment]
It was intentional: wrapping everything in the forEach block let me use the index parameter to make sure descriptions and requirements were associated with the correct Epic.

It is going to require a decent bit of refactoring to un-couple everything: the downside of rushed prototyping
